server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amiiry?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update
